name: "Linux Build and Package"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Version tag"
        required: true
        default: "v0.0.1"
      release:
        description: "Do a release?"
        required: false
        default: false
        type: boolean

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_VERSION: "20.18.0"
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46@sha256:25e022f62120218e83f97adc0f71c3925f0b74f33c6ba94f5cb2b5cf7e975fd7
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Environment Variables
        uses: ./.github/actions/setup-env

      - name: "Determine prerequisites"
        id: prereq
        shell: bash
        run: |
          if command -v node >/dev/null 2>&1; then
            echo "need_node=0" >> $GITHUB_OUTPUT
          else
            echo "need_node=1" >> $GITHUB_OUTPUT
          fi

      # Consider switching to https://github.com/actions/setup-node when it works
      # https://github.com/nektos/act/issues/973
      - name: Install node
        if: ${{ steps.prereq.outputs.need_node == '1' }}
        shell: bash
        run: |
          if [[ "${RUNNER_OS,,}" == "windows" ]]; then
            choco install nodejs -y --version="${NODE_VERSION}"
            echo "C:\Program Files\nodejs" >> $GITHUB_PATH
          else
            curl -sS https://webi.sh/node@${NODE_VERSION} | sh
            echo "${HOME}/.local/opt/node/bin" >> $GITHUB_PATH
          fi

      - name: Build flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: build/flatpak/${{ env.FLATPAK_ID }}.yml
          cache-key: flatpak-builder-${{ github.sha }}
          bundle: ${{ env.COMMON_BUILD_NAME }}-linux-amd64-${{ env.VERSION_TAG }}.flatpak
          upload-artifact: "false"
          verbose: "true"
          # disable-rofiles-fuse: "true"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ env.RELEASE_MODE != 'true' }}
        with:
          name: ${{ env.COMMON_BUILD_NAME }}-linux-amd64-${{ env.VERSION_TAG }}
          path: |
            ${{ env.COMMON_BUILD_NAME }}-linux-amd64-${{ env.VERSION_TAG }}.flatpak

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ env.RELEASE_MODE == 'true' }}
        with:
          tag_name: ${{ env.VERSION_TAG }}
          files: |
            ${{ env.COMMON_BUILD_NAME }}-linux-amd64-${{ env.VERSION_TAG }}.flatpak